<!-- START of: finna - content/privacy_fi.phtml -->

<div class="page-content">
  <h2>Asiakastietojen käsittely Finna Tutkijasalissa</h2>
  <p>Kun käyttäjä kirjautuu ja täyttää käyttöehtolomakkeen Finna Tutkijasali -palveluun tutkijasali. Finna.fi-sivustolta käyttäen suomi.fi-tunnistamista, tallennetaan palveluun seuraavia tietoja:
  </p>
  <p>Finna-palvelu</p>
  <table class="content-table">
    <tbody><tr>
      <td><strong>Tieto</strong></td>
      <td><strong>Tarkoitus</strong></td>
    </tr>
    <tr>
      <th>Käyttäjätunnus</th>
      <td>Käyttäjän tunnistaminen ja yksilöiminen</td>
    </tr>
    <tr>
      <th>Sähköpostiosoite</th>
      <td>Oletusosoite sähköpostin lähetystä varten, käyttäjän muokattavissa Finnassa</td>
    </tr>
    <tr>
      <th>Etunimi</th>
      <td>Tiedon näyttäminen kirjautuneelle käyttäjälle</td>
    </tr>
    <tr>
      <th>Sukunimi</th>
      <td>Tiedon näyttäminen kirjautuneelle käyttäjälle</td>
    </tr>
  </tbody></table>

  <p>Tutkijasalin pääsynhallinta -komponentit</p>
  <table class="content-table">
    <tbody><tr>
      <td><strong>Tieto</strong></td>
      <td><strong>Tarkoitus</strong></td>
    </tr>
    <tr>
      <th>Käyttäjätunnus</th>
      <td>Käyttäjän tunnistaminen ja yksilöiminen</td>
    </tr>
    <tr>
      <th>Sähköpostiosoite</th>
      <td>Sähköpostin lähetystä varten</td>
    </tr>
    <tr>
      <th>Etunimi</th>
      <td>Tiedon näyttäminen kirjautuneelle käyttäjälle</td>
    </tr>
    <tr>
      <th>Sukunimi</th>
      <td>Tiedon näyttäminen kirjautuneelle käyttäjälle</td>
    </tr>
    <tr>
      <th>Käyttötarkoitus</th>
      <td>Tietoturvalle tai -suojalle haittaa aiheuttavien häiriöiden havaitseminen, estäminen, selvittäminen ja esitutkintaan saattaminen</td>
    </tr>
    <tr>
      <th>Käyttöehtojen hyväksyntä</th>
      <td>Tietoturvalle tai -suojalle haittaa aiheuttavien häiriöiden havaitseminen, estäminen, selvittäminen ja esitutkintaan saattaminen</td>
    </tr>
    <tr>
      <th>Ikätieto (yli 15-v.)</th>
      <td>Tietoturvalle tai -suojalle haittaa aiheuttavien häiriöiden havaitseminen, estäminen, selvittäminen ja esitutkintaan saattaminen</td>
    </tr>
    <tr>
      <th>Istunnon alku- ja loppukellonajat</th>
      <td>Tietoturvalle tai -suojalle haittaa aiheuttavien häiriöiden havaitseminen, estäminen, selvittäminen ja esitutkintaan saattaminen</td>
    </tr>
  </tbody></table>

  <p>Tietoja käsitellään Finna-palveluiden toteuttamiseen Kansalliskirjastossa ja CSC – Tieteen tietotekniikan keskus Oy:ssä (palvelun tuottajat).
  </p>
  <p>Finna Tutkijasali -palvelussa käyttäjän on myös mahdollista itse tallentaa ja muuttaa tietojaan. Finnaan tallennettuun sähköpostiosoitteeseen lähetetään vain käyttäjän itse pyytämiä sähköposteja kuten uutuusvahdin tiedonannot.
  </p>
  <p>Edellä mainittujen tietojen lisäksi Finna-palveluun voidaan tallentaa tietoja seurauksena käyttäjän toiminnasta Finnassa. Tällaisia tietoja ovat mm. käyttökieli, uutuusvahdit, omiin listoihin tallennetut tietueet ja sosiaalinen metadata (kommentit, arvostelut, avainsanat).
  </p>
  <p>Käyttäjä voi koska tahansa poistaa Finna-tilin tiedot lakkauttamalla tilinsä palvelussa. <strong>Tietoja ei voi kuitenkaan poistaa Tutkijasalin pääsynhallintakomponentista tieturva- ja tietosuojasyistä.</strong> Finna-tilin tiedot poistuvat automaattisesti, kun viimeisestä kirjautumisesta on kulunut yli 18 kuukautta. Kun tili on poistunut, käyttäjän palveluun mahdollisesti tekemät kommentit ja arvostelut jäävät anonyymeinä eli ilman käyttäjän henkilötietoja palveluun. Jos käyttäjä haluaa poistaa myös kommentit ja arvostelut, se tulee tehdä käsin ennen tilin poistoa. Finna-palvelun käyttäjä voi pyytää tietoa henkilötietojensa käsittelystä ottamalla yhteyttä rekisterinpitäjään. Käyttäjällä on oikeus tietojensa tarkastamiseen ja oikaisuun.
  </p>
  
  <div class="well">Lisätietoa löytyy <a href="register_details">tietosuojaselosteesta</a>.</div>

  <h2>Finna-palvelun aineistot ja henkilötiedot</h2>
  <p>Finna Tutkijasali -palvelun kautta löydettäviksi tarjottavista aineistoista ja niitä kuvailevista tiedoista vastaa aineistot palveluun tuonut organisaatio. Aineistoissa ja kuvailutiedoissa saattaa olla henkilötietoja, kuten henkilönimiä tai -kuvia. Jos aineistoon tai sen kuvailutietoihin liittyvistä henkilötiedoista on tarve esittää kysymyksiä tai esimerkiksi tehdä tietoihin oikaisuja tai vaatia tietojen poistoa, Finna Tutkijasali -palvelun käyttäjä voi olla yhteydessä siihen arkistoon (tai kirjastoon tai museoon), joka on tarjonnut aineiston palveluun. Aineiston tarjoajan tavoittaminen onnistuu tutkijasali.finna.fi-sivustolla kunkin aineiston yhteydestä löytyvällä Ota yhteyttä -lomakkeella.
  </p>
  <p>Jos Finna-palvelun aineistojen käyttäjäkommenteissa on henkilötietoa, jota on tarpeen esim. oikaista tai vaatia poistettavaksi, voi pyynnön esittää kommenttien yhteydestä löytyvällä lomakkeella.
  </p>
  <h2 id="cookies">Evästeiden käyttö</h2>
  <p>Sivuston käyttöä seurataan, jotta palvelua voidaan parantaa. Seurannassa käytetään evästeitä (cookies). Evästeet eivät sisällä mitään sellaista tietoa, jolla käyttäjän voisi yksilöidä tai tunnistaa. Eväste ei vaikuta tietoturvaan, eikä se voi levittää viruksia tai haittaohjelmia. Vierailemalla sivustolla hyväksyt evästeiden käytön.
  </p>
</div>
<!-- END of: finna - content/privacy_fi.phtml -->
