<!-- START of: finna - content/register_details_fi.phtml -->

<div class="page-content">
<p>Katso myös <a href="privacy">tietosuoja-sivu</a>.</p>

   <h3>1. Rekisterin pitäjät</h3>
   <p>Rekisterinpitäjinä toimivat SKS ja Kansalliskirjasto alla mainittujen rajausten pohjalta.</p>
   <p>Suomalaisen Kirjallisuuden Seura:</p>
   <ul class="list-bullets">
      <li>Pääsyrajoitettuihin metatietoihin sisältyvät henkilötiedot.</li>
      <li>Finna Tutkijasali -palveluun tunnistautuvien käyttäjien henkilötiedot REMS- komponenttiin tallennettavien tietojen osalta.</li>
   </ul>
   <p>Kansalliskirjasto:</p>
   <ul class="list-bullets">
      <li>Pääsyrajoitettuihin metatietoihin sisältyvät henkilötiedot.</li>
      <li>Finna Tutkijasali -palveluun tunnistautuvien käyttäjien henkilötiedot Finna-palveluun tallennettavien tietojen osalta.</li>
   </ul>

  <h3>2. Yhteyshenkilö rekisteriä koskevissa asioissa</h3>
  <ul class="list-plain">
      <li>Outi Hupaniittu, arkistonjohtaja</li>
      <li>Suomalaisen Kirjallisuuden Seura</li>
      <li>PL 259 (Hallituskatu 1)</li>
      <li>00171 Helsinki</li>
      <li>Sähköposti: ahaa@finlit.fi</li>
  </ul>
  <ul class="list-plain">
      <li>Erkki Tolonen, kehittämispäällikkö</li>
      <li>Kirjastoverkkopalvelut</li>
      <li>Kansalliskirjasto</li>
      <li>PL 15 (Unioninkatu 36)</li>
      <li>00014 Helsingin yliopisto</li>
      <li>Sähköposti: finna-posti@helsinki.fi</li>
  </ul>

  <h3>3. Rekisterin nimi</h3>
  <p>Finna Tutkijasali -palvelussa käsiteltävät henkilötiedot</p>

  <h3>4. Henkilötietojen käsittelyn tarkoitus ja käsittelyn peruste</h3>
  <p>Henkilötietoja käsitellään Finna Tutkijasali -palveluun kirjautuvan käyttäjän tunnistamiseksi ja käyttöoikeuksien hallinnoimiseen. Tunnistautumisessa käytetään vahvaa tunnistautumista ja tunnistuksenohjauspalveluna on suomi.fi.
  </p>
  <p>Henkilötietoja käsitellään myös, jotta käyttäjälle voidaan tarjota asiakastoimintoja ja personoituja palveluita Finna Tutkijasali -palvelun avulla. Esimerkki personoidusta palvelusta on uutuusvahtipalvelu, jolla asiakas saa niin halutessaan sähköpostitse tiedot hakuun tulleista uusista viitteistä.
  </p>
  <p>Finna Tutkijasali -palvelun kautta löydettäviksi tarjottavista aineistoissa ja niitä kuvailevissa metatiedoissa saattaa olla henkilötietoja. Näistä aineistoista vastaa aineistot palveluun tuonut organisaatio.
  </p>
  <p>Henkilötietoja käsitellään myös palvelun käyttöön ja kehittämiseen liittyvään tilastointiin ja hallintaan.
  </p>
  <p>Kun käyttäjä tulee tähän verkkopalveluun, tieto tapahtumasta (mm. IP-osoite) tallentuu väliaikaisesti käsiteltäväksi.
  </p>
  <p>Käsittelyn perusteena on rekisterinpitäjän oikeutettu etu.
  </p>

  <h3>Rekisterin tietosisältö</h3>
  <h4>Käyttäjän perustiedot</h4>
  <ul class="list-bullets">
      <li>Käyttäjätunnus</li>
      <li>Nimi</li>
      <li>Henkilötunnus (vahvasti salattuna)</li>
      <li>Sähköpostiosoite</li>
      <li>Palvelun käyttötarkoitus</li>
      <li>Käyttäjän vakuutus hänen olevan yli 15</li>
      <li>Istunnon alku- ja loppukellonajat</li>
      <li>Tehtyjen hakujen määrä</li>
  </ul>
  <h4>Finna-palveluun kerättävät tiedot</h4>
  <ul class="list-bullets">
      <li>Käyttäjätunnus</li>
      <li>Nimi</li>
      <li>Sähköpostiosoite</li>
      <li>Käyttäjän henkilökohtaiset asetukset</li>
      <li>Käyttökieli</li>
      <li>Suosikit</li>
  </ul>

  <h3>6. Säännönmukaiset tietolähteet</h3>
  <p>Tiedot haetaan Suomi.fi-tunnistamisesta ja käyttäjä tallentaa tietoja itse palveluun.
  </p>

  <h3>7. Arkaluonteisten henkilötietojen käsittely ja suojaaminen</h3>
  <p>Arkaluonteisia henkilötietoja ei käsitellä palvelussa. Henkilötunnus salataan vahvasti käyttäjän tunnistautumisen yhteydessä ja siitä muodostetaan anonymisoitu käyttäjätunniste. Henkilötunnusta ei tämän jälkeen näytetä palvelussa. Henkilötunnuksen voi avata tilanteiden selvittelyyn vain väärinkäytöstapauksissa. Tällaisiin tietoihin pääsevät käsiksi ainoastaan järjestelmän ylläpitäjät, jotka tunnistetaan käyttäjätunnuksella ja salasanalla.
  </p>

  <h3>8. Henkilötietojen säilytysaika ja tarpeettomien henkilötietojen poistaminen</h3>
  <p>Finna Tutkijasalin pääsynhallintakomponenteissa tiedot (henkilötunnus, nimi, sähköpos-tiosoite) säilyvät viisi vuotta.
  </p>
  <p>Käyttäjän Finna-tiliin liittyviä tietoja säilytetään Finna Tutkijasali -palvelussa, kunnes vii-meisestä kirjautumisesta on kulunut 18 kuukautta.
  </p>
  <p>Käyttäjään yhdistettävien tehtyjen hakujen määrän tietoa säilytetään 30 päivää, jonka jälkeen tieto poistetaan. Tutkijasalin pääsynhallintakomponentissa kaikki lokitiedot säilytetään viisi vuotta.
  </p>

  <h3>9. Automatisoitu henkilötietojen käsittely ja profilointi</h3>
  <p>Henkilötietoja ei käytetä automaattiseen päätöksentekoon tai profilointiin.</p>

  <h3>10. Tietojen säännönmukaiset luovutukset</h3>
  <p>Tietoja ei luovuteta ulkopuolisille tahoille.
  </p>

  <h3>11. Tietojen siirto EU:n tai ETA:n ulkopuolelle</h3>
  <p>Tietoja ei siirretä EU:n tai ETA:n ulkopuolelle.</p>

  <h3>12. Rekisterin suojauksen periaatteet</h3>
  <p>Tietoja säilytetään ainoastaan sähköisessä muodossa. Tietoihin pääsevät käsiksi ainoastaan järjestelmän ylläpitäjät, jotka tunnistetaan käyttäjätunnuksella ja salasanalla.
  </p>

  <h3>13. Tarkastusoikeus</h3>
  <p>Tarkistaakseen, mitä henkilötietoja käyttäjästä on kerätty palveluun, käyttäjän tulee ottaa yhteys palvelun ylläpitäjään Finna Tutkijasali -sivuston palautelomakkeella https://tutkijasali.finna.fi/Feedback/Home.
  </p>

  <h3>14. Oikeus vaatia tiedon korjaamista ja poistamista</h3>
  <p>Käyttäjä voi milloin tahansa poistaa Finna-tilin tietonsa palvelusta poistamalla tilinsä palvelussa. Käyttäjä ei voi itse poistaa pääsynhallintakomponentissa olevia itseensä liittyviä tietoja eikä lokitietoja.
  </p>
  <p>Käyttäjä voi olla yhteydessä rekisterinpitäjään.
  </p>
  <p>Jos aineistoon tai sen kuvailutietoihin liittyvistä henkilötiedoista on tarve esittää kysymyksiä tai esimerkiksi tehdä tietoihin oikaisuja tai vaatia tietojen poistoa, Finna Tutkijasali -palvelun käyttäjä voi olla yhteydessä siihen arkistoon, kirjastoon tai museoon, joka on tarjonnut aineiston palveluun. Aineiston tarjoajan tavoittaminen onnistuu tutkijasali.Finna.fi-sivustolla kunkin aineiston yhteydestä löytyvällä Ota yhteyttä -lomakkeella.
  </p>

  <h3>15. Muut henkilötietojen käsittelyyn liittyvät oikeudet</h3>
  <p>Käyttäjällä on oikeus saattaa palvelun toiminnan lainmukaisuus Tietosuojavaltuutetun arvioitavaksi: tietosuoja(at)om.fi.</p>

</div>

<!-- END of: finna - content/register_details_fi.phtml -->
