<!-- START of: custom - content/tutkijasali_fi.phtml -->
<?php $this->headTitle($this->translate('R2_menu_heading'));?>
<?php if ($this->resolver('tutkijasaliBegin_fi.phtml')): ?>
  <?=$this->render('tutkijasaliBegin_fi.phtml')?>
<?php endif; ?>
<?php if ($this->resolver('content/tutkijasali-tabs.phtml')): ?>
  <?=$this->render('content/tutkijasali-tabs.phtml', ['activeTab' => 'tutkijasali'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <div id="begin1" class="content-section">
    <h2>Ohjeet Finnan tutkijasaliin</h2>
    <ol class="list-decimal">
      <li>Klikkaa oikeassa yläkulmassa olevaa Kirjaudu-painiketta ja valitse suomi.fi-kirjautuminen.</li>
      <li>Tunnistaudu Suomi.fi-tunnistamismenetelmällä (vahva tunnistaminen, esim. verkkopankkitunnuksilla).</li>
      <li>Täytä tunnistamisen jälkeen avautuva käyttöehtolomake.</li>
      <li>Kerro lomakkeella käyttötarkoituksesi aineistotiedoille ja aineistoille, hyväksy käyttöehdot sekä täydennä yhteystietosi.</li>
      <li>Lähetä lomake.</li>
    </ol>
    <p>Voit nyt kohdistaa hakuja myös kaikkiin palvelun sisältämiin tietosuojattuihin aineistotietoihin ja nähdä ne aineistosivuilla.</p>

    <h3>Tietoa tutkijasalin käyttämisestä</h3>
    <p>Tietosi tallennetaan Finnan käyttäjärekisteriin ja REMS-luvituspalveluun (CSC). <a href="<?=$this->url('myresearch-r2termsofuse')?>">Lue lisää tietosuojaselosteesta</a>. Päivittäisen käytön määrää on rajattu tietoturvasyistä. Mikäli Finnan tutkijasalin käyttösi katkaistaan kesken työskentelyn, voit ottaa yhteyttä XXX@xxx.fi tai käyttää tutkijasalia seuraavana päivänä taas tavalliseen tapaan. Päivittäisen käytön määrä tallentuu seurantalokiin. Nämä lokit poistetaan xx päivän kuluttua, jos poikkeavuuksia ei ole esiintynyt.</p>
    <p>Finnan tutkijasalin haku ja hakutoiminnot vastaavat Finna.fi-hakupalvelun hakua muilta kuin suojattujen aineistojen osalta. <a href="<?=$this->url('content-page', ['page' => 'help'])?>">Yleisiä hakuohjeita.</a></p>
  </div>
  <div id="begin2" class="content-section">
    <h2>Sisältö ja rajaukset</h2>
    <p>Finnan tutkijasalipalvelu sisältää tällä hetkellä pilottiaineistona käytetyt Suomalaisen Kirjallisuuden Seuran (SKS) arkistoaineistojen aineistotiedot (luettelointitiedot).</p>
    <p>Projektin seuraavissa vaiheissa toteutaan myös rajoitusten alaisten aineistojen käyttö verkossa sekä arkaluontoisia henkilötietoja sisältävien kuvailutietojen näyttäminen erillisen lupa-anomuksen hyväksynnän jälkeen.</p>
  </div>
  <div id="begin3" class="content-section">
    <h2>Aineistotietojen käyttöehdot</h2>
    <p>Finnan tutkijasalin  sisältämiä aineistotietoja (kuvailutietoa, luettelointitietoa, metatietoja) voi käyttää tietosuoja-asetuksen ja tietosuojalain asettamin rajoituksin. Käyttäjällä on oikeus hakea ja selata aineistotietoja. Käyttäjä sitoutuu käyttämään aineistotietoa ja aineistoja ilmoittamansa käyttötarkoituksen mukaisesti.</p>
    <p>Jos käyttäjä toimii Palvelun käyttöehtojen, lainsäädännön tai hyvien tapojen vastaisesti, Palvelun ylläpitäjä voi lopettaa käyttöoikeuden ja poistaa käyttäjätunnuksen. Käyttäjä vastaa kaikesta vahingosta, joka on aiheutunut arkistolle tai kolmannelle osapuolelle siitä, että käyttäjä on toiminut näiden käyttöehtojen, lainsäädännön, viranomaismääräysten tai hyvien tapojen vastaisesti.</p>
  </div>
  <div id="begin4" class="content-section">
    <h2>Palvelussa käytetyt käsitteet</h2>

    <h3>Aineistotieto</h3>
    <p>Finnassa aineistotieto tarkoittaa kaikkia metatietoja, nämä sisältävät sekä kuvailevan metatiedon että luettelointitiedon. Suureen osaan Finnaan tuodusta aineistotiedosta voi kohdistaa hakuja.</p>

    <h3>Henkilötieto</h3>
    <p>Henkilötietoja ovat sellaiset tiedot, joiden perusteella henkilö voidaan tunnistaa suoraan tai välillisesti esimerkiksi yhdistämällä yksittäinen tieto johonkin toiseen tietoon, joka mahdollistaa tunnistamisen. Henkilö voidaan tunnistaa esimerkiksi nimen, henkilötunnuksen tai jonkin hänelle tunnusomaisen tekijän perusteella. Lähde: Tietosuojavaltuutettu.</p>

   <h3>Erityinen henkilötietoryhmä</h3>
   <p>Tällaisista tiedoista ilmenee henkilön</p>
   <ul class="list-bullets">
     <li>rotu tai etninen alkuperä</li>
     <li>poliittisia mielipiteitä</li>
     <li>uskonnollinen tai filosofinen vakaumus</li>
     <li>ammattiliiton jäsenyys</li>
     <li>terveyttä koskevia tietoja</li>
     <li>seksuaalinen suuntautuminen tai käyttäytyminen</li>
     <li>geneettisiä ja biometrisia tietoja henkilön tunnistamista varten</li>
   </ul>

   <h3>Käyttösitoumus</h3>
   <p>Käyttäjän tietoihin jäävä merkintä siitä, että käyttäjä sitoutuu käyttämään palvelun sisältämiä aineistoja tai aineistotietoja vain luvallisilla tavoilla.</p>
   
   <h3>Pääsy tai pääsyoikeus</h3>
   <p>Tunnistetulle identiteetille myönnetään tämän käyttötarkoituksen mukaiset käyttövaltuudet määriteltyihin aineistotietoihin tai aineistoihin.</p>

   <h3>Tietosuoja</h3>
   <p>Tietosuoja on perusoikeus, joka turvaa rekisteröidyn oikeuksien ja vapauksien toteutumisen henkilötietojen käsittelyssä. Tietosuojan tarkoituksena on osoittaa, milloin ja millä edellytyksillä henkilötietoja voidaan käsitellä. Henkilötietojen käsittelyn on aina perustuttava lakiin. (tietosuoja.fi)</p>
  </div>
</div>
<!-- END of: custom - content/tutkijasali_fi.phtml -->