<!-- START of: custom - content/tutkijasali_organisaatiot-fi.phtml -->
<?php $this->headTitle($this->translate('R2_menu_heading'));?>
<?php if ($this->resolver('tutkijasaliBegin_fi.phtml')): ?>
  <?=$this->render('tutkijasaliBegin_fi.phtml')?>
<?php endif; ?>
<?php if ($this->resolver('content/tutkijasali-tabs.phtml')): ?>
  <?=$this->render('content/tutkijasali-tabs.phtml', ['activeTab' => 'tutkijasali-organisaatiot'])?>
<?php endif; ?>
<div class="mainbody">
  <h2>Mukana olevat organisaatiot</h2>
  <p>Lorem ipsum</p>
  <p><a href="https://finna.fi">Suomalaisen kirjallisuuden seura</a></p>
</div>
<!-- END of: custom - content/tutkijasali-organisaatiot_fi.phtml -->