<!-- START of: custom - content/tutkijasali-ukk_fi.phtml -->
<?php $this->headTitle($this->translate('R2_menu_heading'));?>
<?php if ($this->resolver('tutkijasaliBegin_fi.phtml')): ?>
  <?=$this->render('tutkijasaliBegin_fi.phtml')?>
<?php endif; ?>
<?php if ($this->resolver('content/tutkijasali-tabs.phtml')): ?>
  <?=$this->render('content/tutkijasali-tabs.phtml', ['activeTab' => 'tutkijasali-ukk'])?>
<?php endif; ?>
<div class="mainbody">
  <h2>Usein kysytyt kysymykset</h2>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading1">
        <h3 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
            <i class="fa fa-arrow-down open-icon"></i>
            <i class="fa fa-arrow-up close-icon"></i>
            Miksi minun pitää kirjautua pankkitunnuksilla Finnan Tutkijasaliin?
          </a>
        </h3>
      </div>
      <div id="collapse1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
        <div class="panel-body">
          <p>Suojattujen henkilötietojen käyttö edellyttää henkilöllisyyden varmistamista luotettavasti. Pääsy henkilötietoihin myös tallennetaan mahdollista myöhempää käyttöä varten. Tietosuojaselosteessa kerrotaan tietojesi tallentamisesta.</p>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading2">
        <h3 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
            <i class="fa fa-arrow-down open-icon"></i>
            <i class="fa fa-arrow-up close-icon"></i>
            Miksi minun täytyy sitoutua käyttöehtoihin joka käyttökerralla?
          </a>
        </h3>
      </div>
      <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
        <div class="panel-body">
          <p>Käyttöehtoihin sitoutuminen ja käyttötarkoitus ilmoitetaan jokaisella kirjautumiskerralla erikseen, jotta varmistetaan suojattujen tietojen käyttäminen vain lainmukaisessa tarkoituksessa.</p>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading3">
        <h3 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="false" aria-controls="collapse3">
            <i class="fa fa-arrow-down open-icon"></i>
            <i class="fa fa-arrow-up close-icon"></i>
            Miksi minut kirjataan ulos? Miksi käyttöistuntoni päättyy itsestään?
          </a>
        </h3>
      </div>
      <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
        <div class="panel-body">
          <p>Finna Tutkijasalin käyttösessio katkeaa, jos palvelu on käyttämättä 30 minuuttia. Aikakatkaisu tehdään tietoturvan vuoksi, tällöin vahingossa auki jäänyt istunto ei päädy niin helposti muiden käyttöön. Muista kuitenkin aina kirjautua itse ulos, kun lopetat tutkijasalin käytön.</p>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading4">
        <h3 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="false" aria-controls="collapse4">
            <i class="fa fa-arrow-down open-icon"></i>
            <i class="fa fa-arrow-up close-icon"></i>
              Miksi uutuusvahdissani ei näy kaikkia uusia aineistoja?
          </a>
        </h3>
      </div>
      <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading4">
        <div class="panel-body">
          <p>Uutuusvahti ei sisällä sellaisia aineistoja, joiden koko aineistotietokokonaisuus on suojattua kuvailutietoa otsikkotasolta lähtien. Tällaisten aineistojen tietoja ei voi lähettää sähköpostitse. Saat suojatutkin aineistotiedot mukaan kirjautumalla Finna Tutkijasaliin ja rajaamalla haun Uutta tutkijasalissa -suodattimella.</p>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading5">
        <h3 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="false" aria-controls="collapse5">
            <i class="fa fa-arrow-down open-icon"></i>
            <i class="fa fa-arrow-up close-icon"></i>
              Miksi RSS-syötteessäni ei näy kaikkia aineistoja?
          </a>
        </h3>
      </div>
      <div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading5">
        <div class="panel-body">
          <p>RSS-syötteessä ei näy aineistoja, joiden koko aineistotietokokonaisuus on suojattua kuvailutietoa otsikkotasolta lähtien. Tällaiset aineistot näkyvät vain tunnistautuneille ja tutkijasalin sisältämien aineistotietojen käyttöehtoihin sitoutuneille käyttäjille.</p>
        </div>
      </div>
    </div>

  </div>
</div>
<!-- END of: custom - content/tutkijasali-ukk_fi.phtml -->