<!-- START of: custom - Content/tutkijasali-tabs.phtml -->
<div class="finna-main-tabs">
    <ul class="nav nav-tabs help-tabs hidden-xs" role="tablist">
        <li class="help-tab <?= $activeTab === 'tutkijasali' ? ' active" aria-selected="true"' : '" aria-selected="false"' ?> role="tab" tabindex="0" data-url="<?=$this->url('content-page', ['page' => 'tutkijasali'])?>">
            <?=$this->transEsc("tabs_tutkijasali");?>
        </li>
        <li class="help-tab <?= $activeTab === 'tutkijasali-ukk' ? ' active" aria-selected="true"' : '" aria-selected="false"' ?> role="tab" tabindex="0" data-url="<?=$this->url('content-page', ['page' => 'tutkijasali-ukk'])?>">
            <?=$this->transEsc("tabs_tutkijasali_ukk");?>
        </li>
        <li class="help-tab <?= $activeTab === 'tutkijasali-organisaatiot' ? ' active" aria-selected="true"' : '" aria-selected="false"' ?> role="tab" tabindex="0" data-url="<?=$this->url('content-page', ['page' => 'tutkijasali-organisaatiot'])?>">
            <?=$this->transEsc("tabs_tutkijasali_organisaatiot");?>
        </li>
    </ul>
    <div class="mobile-main-tabs visible-xs">
        <div class="dropdown visible-xs">
            <div class="dropdown-toggle clearfix" data-toggle="dropdown">
                <div class="tab-title"><?=$this->translate('tabs_' . $activeTab);?></div>
                <div class="more"><?=$this->transEsc("More");?><b class="caret"></b></div>
            </div>
            <ul class="dropdown-menu" role="menu">
                <li role="menuitem" <?php if($activeTab === 'tutkijasali'): ?> class="active" <?php endif; ?>>
                    <a href="<?=$this->url('content-page', ['page' => 'tutkijasali'])?>"><?=$this->transEsc('tabs_tutkijasali');?></a>
                </li>
                <li role="menuitem" <?php if($activeTab === 'tutkijasali_ukk'): ?> class="active" <?php endif; ?>>
                    <a href="<?=$this->url('content-page', ['page' => 'tutkijasali-ukk'])?>"><?=$this->transEsc('tabs_tutkijasali_ukk');?></a>
                </li>
                <li role="menuitem" <?php if($activeTab === 'tutkijasali_organisaatiot'): ?> class="active" <?php endif; ?>>
                    <a href="<?=$this->url('content-page', ['page' => 'tutkijasali-organisaatiot'])?>"><?=$this->transEsc('tabs_tutkijasali_organisaatiot');?></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END of: custom - Content/tutkijasali-tabs.phtml -->
