<div class="tutkijasali-banner">
  <div class="row">
    <div class="col-xs-12">
        <h1>Finna Reading Room</h1>
    </div>
</div>

<div class="grey">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h3>Finna Reading Room in a nutshell</h3>
        <p>Finna Reading Room contains <strong>metadata</strong> with access restrictions, which means that they cannot be accessed freely. To search for protected personally identifiable information from all the metadata contained in the service, you need to log in to the service and agree to the terms of use. In the future, the Reading Room will also contain <strong>digital materials</strong> (to which access restrictions may apply for various reasons).</p>
        <p>Finna Reading Room is a search service provided under a pilot project by the National Library’s Finna search services and CSC – IT Center for Science for browsing materials that contain protected metadata. To see all Finna’s participating organisations and materials, go to the national <a href="https://finna.fi">finna.fi search service</a>.</p>
        <?php if ($this->R2()->isRegistered() && $this->R2()->hasUserAccess(true)): ?>
          <?= $this->R2()->registeredInfo(null, ['hideInfo' => true])?>
        <?php endif; ?>
      </div>
      <div class="col-md-4">
        <div class="img-wrapper">
          <img src="<?= $this->imageSrc('tutkijasali.jpg')?>" alt="">
          <div class="text">Nyblin Daniel, photographer. Valtionarkiston tutkijasali, 1901. CC BY 4.0 Museovirasto</div>
        </div>
      </div>    
    </div>
  </div>
</div>
