<div class="tutkijasali-banner">
  <div class="row">
    <div class="col-xs-12">
        <h1>Finnan tutkijasali</h1>
    </div>
</div>

<div class="grey">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h3>Finnan tutkijasali pähkinänkuoressa</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <?php if ($this->R2()->isRegistered() && $this->R2()->hasUserAccess(true)): ?>
        <?= $this->R2RestrictedRecordRegistered(null, ['user' => $this->auth()->isLoggedIn(), 'hideInfoLink' => true])?>
<?php else: ?>
        <?= $this->R2RestrictedRecordRegister(null, ['user' => $this->auth()->isLoggedIn(), 'hideNote' => true, 'hideInfoLink' => true, 'ignoreCache' => true])?>
        <?php endif; ?>
      </div>
      <div class="col-md-4">
        <div class="img-wrapper">
          <img src="<?= $this->imageSrc('tutkijasali.jpg')?>" alt="">
          <div class="text">Nyblin Daniel, kuvaaja. Valtionarkiston tutkijasali, 1901. CC BY 4.0 Museovirasto</div>
        </div>
      </div>    
    </div>
  </div>
</div>