<div class="tutkijasali-banner">
  <div class="row">
    <div class="col-xs-12">
        <h1>Finna Tutkijasali</h1>
    </div>
</div>

<div class="grey">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h3>Finna Tutkijasali pähkinänkuoressa</h3>
        <p>Finna Tutkijasalista löydät aineistoja, aineistoluettoja ja aineistotietoja, joiden näyttämistä (pääsy) on rajoitettu. Voit kohdistaa hakuja kaikkiin palvelun aineistotietojen sisältämiin suojattuihin henkilötietoihin kirjautumalla ja sitoutumalla käyttöehtoihin. Tulevaisuudessa tutkijasalissa voi saada pääsyn myös rajoitettuihin digitaalisiin aineistoihin.</p>
        <?php if ($this->R2()->isRegistered() && $this->R2()->hasUserAccess(true)): ?>
        <?= $this->R2RestrictedRecordRegistered(null, ['user' => $this->auth()->isLoggedIn(), 'hideInfoLink' => true])?>
<?php else: ?>
        <?= $this->R2RestrictedRecordRegister(null, ['user' => $this->auth()->isLoggedIn(), 'hideNote' => true, 'hideInfoLink' => true, 'ignoreCache' => true])?>
        <?php endif; ?>
      </div>
      <div class="col-md-4">
        <div class="img-wrapper">
          <img src="<?= $this->imageSrc('tutkijasali.jpg')?>" alt="">
          <div class="text">Nyblin Daniel, kuvaaja. Valtionarkiston tutkijasali, 1901. CC BY 4.0 Museovirasto</div>
        </div>
      </div>    
    </div>
  </div>
</div>