<!-- START of: finna - search/home/home-1.phtml -->
<?= $this->flashmessages() ?>
<div class="container">
  <div class="col-sm-6">
    <h2>Virtuaalinen Tutkijasali tarjoaa löytöjä kotikoneelta</h2>
    <p>Finna Tutkijasalista löydät arkistojen aarteita! Palvelusta voit löytää monenlaisten aineistojen lisäksi tietosuojattuja <strong>aineistotietoja</strong> (metatieto), joiden näyttämistä on rajoitettu, eikä pääsy niihin ole vapaata. Voit kohdistaa hakuja kaikkiin palvelun aineistotietojen sisältämiin suojattuihin henkilötietoihin kirjautumalla Tutkijasaliin ja sitoutumalla käyttöehtoihin.</p>
    <p>Tulevaisuudessa Tutkijasalissa voi saada pääsyn myös tietosuojattuihin <strong>digitaalisiin aineistoihin</strong> avoimien aineistojen lisäksi.</p>
  </div>
  <div class="col-sm-6 r2-info">
    <?php $user = $this->auth()->isLoggedIn(); ?>
    <?php if (!$user || !$this->R2()->isRegistered(true)): ?>
      <h2>Ohjeet Finna Tutkijasaliin</h2>
      <?= $this->R2()->register(null, ['ignoreCache' => true, 'hideInfo' => true])?>
    <?php else: ?>
      <h2>Olet kirjautunut Finna Tutkijasaliin</h2>
      <div class="r2-restricted-info">
        <div><i class="fa fa-research fa-4x"></i></div>
        <div><?= $this->translate('R2_restricted_info_html') ?></div>
      </div>
   <?php endif ?>
   <blockquote class="finnafi-blockquote">
     <p><a href="<?= $this->url('content-page', ['page' => 'help']) ?>">Kurkkaa Finnan hakuohjeet</a>, jos kaipaat vinkkejä hakemiseen ja rajaamiseen.</p>
   </blockquote>
  </div>
</div>
<!-- END of: finna - search/home/home-1.phtml -->
